export const DRAWABLE_WORDS = [
  'gato', 'perro', 'pez', 'pájaro', 'tortuga', 'conejo', 'elefante', 'jirafa',
  'serpiente', 'mariposa', 'abeja', 'pulpo', 'rana', 'pato', 'gallina', 'caballo',
  'vaca', 'cerdo', 'oveja', 'león', 'oso', 'pingüino', 'caracol', 'ratón',
  'tigre', 'cebra', 'mono', 'koala', 'panda', 'zorro', 'lobo', 'ciervo',
  'búho', 'águila', 'paloma', 'cuervo', 'cisne', 'flamenco', 'pelícano', 'delfín',
  'ballena', 'tiburón', 'cangrejo', 'medusa', 'foca', 'hipopótamo', 'rinoceronte', 'cocodrilo',
  'lagarto', 'camaleón', 'iguana', 'murciélago', 'ardilla', 'erizo', 'mapache', 'canguro',
  'avestruz', 'pavo', 'loro', 'canario', 'hámster', 'cabra', 'burro', 'camello',
  'llama', 'jabalí', 'nutria', 'castor', 'sapo', 'libélula', 'hormiga', 'araña',
  'mariquita', 'oruga', 'calamar', 'caballito de mar', 'estrella de mar', 'lechuza', 'ganso', 'halcón',
  'gorila', 'chimpancé', 'orangután', 'perezoso', 'suricata', 'mofeta', 'alce', 'bisonte',
  'ñu', 'okapi', 'tapir', 'armadillo', 'capibara', 'chinchilla', 'comadreja', 'lince',
  'pantera', 'guepardo', 'hiena', 'canguro rojo', 'wombat', 'ornitorrinco', 'kiwi', 'tucán',
  'cormorán', 'garza', 'cigüeña', 'grulla', 'codorniz', 'perdiz', 'faisán', 'gaviota',
  'foca bebé', 'morsa', 'narval', 'mantarraya', 'pez globo', 'pez espada', 'trucha', 'atún',
  'langosta', 'camarón', 'ostra', 'almeja', 'caracol de mar', 'escarabajo', 'saltamontes', 'grillo',
  'mosquito', 'mosca', 'luciérnaga', 'gusano', 'lombriz', 'ciempiés', 'escorpión',
  'casa', 'sol', 'luna', 'estrella', 'árbol', 'flor', 'coche', 'bicicleta',
  'barco', 'avión', 'tren', 'sombrero', 'gafas', 'reloj', 'llave', 'libro',
  'taza', 'plato', 'silla', 'mesa', 'cama', 'puerta', 'ventana', 'escalera',
  'paraguas', 'globo', 'pelota', 'guitarra', 'zapato', 'mochila', 'helado', 'manzana',
  'plátano', 'pizza', 'pastel', 'huevo', 'zanahoria', 'montaña', 'puente', 'castillo',
  'faro', 'cohete', 'nube', 'rayo', 'bandera', 'corona', 'espada', 'ancla',
  'semáforo', 'autobús', 'camión', 'moto', 'helicóptero', 'robot', 'florero', 'lápiz',
  'tijeras', 'martillo', 'cepillo', 'jabón', 'toalla', 'almohada', 'lámpara', 'televisor',
  'cámara', 'balón', 'raqueta', 'patín', 'cometa', 'tela de araña', 'hueso', 'queso',
  'naranja', 'pera', 'uva', 'fresa', 'sandía', 'melón', 'piña', 'limón',
  'cereza', 'durazno', 'kiwi fruta', 'coco', 'aguacate', 'tomate', 'pepino', 'lechuga',
  'brócoli', 'maíz', 'papa', 'cebolla', 'ajo', 'pimiento', 'calabaza', 'berenjena',
  'pan', 'galleta', 'dona', 'croissant', 'waffle', 'hot dog', 'hamburguesa', 'taco',
  'sándwich', 'palomitas', 'pretzel', 'churro', 'cupcake', 'rosquilla', 'galletas', 'barra de pan',
  'leche', 'jugo', 'botella', 'vaso', 'cucharón', 'tenedor', 'cuchillo', 'cucharita',
  'olla', 'sartén', 'hervidor', 'tetera', 'jarra', 'salero', 'salero de pimienta', 'tabla de cortar',
  'horno', 'refrigerador', 'microondas', 'tostadora', 'licuadora', 'cafetera', 'plancha', 'lavadora',
  'escoba', 'recogedor', 'trapeador', 'cubeta', 'esponja', 'detergente', 'papel higiénico', 'jabonera',
  'ducha', 'bañera', 'lavabo', 'inodoro', 'espejo', 'peine', 'cepillo de dientes', 'pasta dental',
  'secador', 'navaja', 'toalla de mano', 'alfombra', 'cortina', 'cojín', 'manta', 'edredón',
  'sofá', 'sillón', 'escritorio', 'estante', 'librero', 'cajón', 'armario', 'perchero',
  'cuadro', 'reloj de pared', 'vela', 'candelabro', 'maceta', 'cactus', 'bonsái', 'helecho',
  'palmera', 'pino', 'roble', 'seta', 'hongo', 'hoja', 'rama', 'tronco',
  'nido', 'colmena', 'barril', 'cesta', 'canasta', 'caja', 'regalo', 'lazo',
  'sobre', 'sello', 'carta', 'periódico', 'revista', 'mapa', 'brújula', 'telescopio',
  'microscopio', 'probeta', 'imán', 'pila', 'enchufe', 'bombilla', 'linterna', 'vela de cumpleaños',
  'pastel de cumpleaños', 'sombrero de fiesta', 'globo de cumpleaños', 'piñata', 'confeti', 'máscara', 'careta', 'disfraz',
  'capa', 'varita', 'escoba de bruja', 'caldero', 'poción', 'calavera', 'hueso cruzado', 'cofre',
  'mapa del tesoro', 'pirata', 'loro pirata', 'barco pirata', 'timón', 'catalejo', 'cañón', 'bala de cañón',
  'castillo de arena', 'cubeta de playa', 'pala de playa', 'flotador', 'tabla de surf', 'boya', 'red de pesca', 'caña de pescar',
  'anzuelo', 'chaleco', 'salvavidas', 'submarino', 'buzo', 'aleta', 'snorkel', 'isla',
  'volcán', 'cueva', 'cascada', 'río', 'lago', 'ola', 'caracola', 'piedra',
  'roca', 'canto rodado', 'igloo', 'muñeco de nieve', 'copo de nieve', 'trineo', 'esquí', 'patineta',
  'monopatin', 'bicicleta de montaña', 'triciclo', 'patinete', 'carro', 'carreta', 'carretilla', 'tractor',
  'excavadora', 'grúa', 'montacargas', 'camión de bomberos', 'ambulancia', 'patrulla', 'taxi', 'limusina',
  'furgoneta', 'remolque', 'caravana', 'casa rodante', 'globo aerostático', 'dirigible', 'paracaídas', 'planeador',
  'ala delta', 'ovni', 'satélite', 'telescopio espacial', 'planeta', 'cohete de juguete', 'astronauta', 'casco espacial',
  'alien', 'robot de juguete', 'dinosaurio', 'huevo de dinosaurio', 'huella', 'fósil', 'volcán pequeño', 'meteorito',
  'arcoíris', 'tornado', 'huracán', 'paraguas cerrado', 'botas', 'botas de lluvia', 'chanclas', 'sandalias',
  'tenis', 'tacones', 'sombrero de copa', 'gorra', 'boina', 'bufanda', 'guantes', 'calcetines',
  'camisa', 'pantalón', 'vestido', 'falda', 'chaqueta', 'abrigo', 'corbata', 'moño',
  'anillo', 'collar', 'pendientes', 'pulsera', 'reloj de pulsera', 'monedero', 'billetera', 'bolso',
  'maleta', 'maletín', 'cepillo de pelo', 'pinza', 'horquilla', 'lazo de pelo', 'diadema', 'corona de flores',
  'rosa', 'tulipán', 'girasol', 'margarita', 'clavel', 'orquídea', 'loto', 'hoja de trébol',
  'trébol', 'cactus en maceta', 'regadera', 'pala', 'rastrillo', 'hoz', 'azada', 'carretilla de jardín',
  'espantapájaros', 'invernadero', 'banco del parque', 'farol', 'busto', 'estatua', 'fuente', 'pozo',
  'molino', 'molino de viento', 'granero', 'establo', 'cerca', 'portón', 'buzón', 'hidrante',
  'cono de tránsito', 'señal de alto', 'paso de cebra', 'bicicleta estacionada', 'casco', 'campana', 'timón de bici', 'canasta de bici',
  'patines', 'patines de hielo', 'palo de hockey', 'disco de hockey', 'bate', 'guante de béisbol', 'pelota de béisbol', 'aro de básquet',
  'canasta de básquet', 'portería', 'balón de fútbol', 'silbato', 'medalla', 'trofeo', 'podio', 'antorcha',
  'diana', 'flecha', 'arco', 'espada de juguete', 'escudo', 'casco de caballero', 'lanza', 'hacha',
  'maza', 'ballesta', 'catapulta', 'torre', 'muralla', 'puente levadizo', 'foso', 'dragón',
  'caballero', 'princesa', 'rey', 'reina', 'mago', 'bruja', 'duende', 'hada',
  'gnomo', 'enano', 'troll', 'ogro', 'unicornio', 'pegaso', 'fénix', 'grifo',
  'sirena', 'yeti', 'frankestein', 'momia', 'vampiro', 'hombre lobo', 'fantasma', 'calabaza de halloween',
  'linterna de calabaza', 'murciélago de halloween', 'escoba voladora', 'gato negro', 'caldero burbujeante', 'poción verde', 'libro de hechizos', 'varita mágica',
  'cristal', 'bola de cristal', 'amuleto', 'llave antigua', 'cerradura', 'candado', 'caja fuerte', 'lingote',
  'moneda', 'billete', 'hucha', 'alcancía', 'calculadora', 'ábaco', 'regla', 'escuadra',
  'compás', 'transportador', 'clip', 'grapadora', 'perforadora', 'cinta adhesiva', 'pegamento', 'tijeras de oficina',
  'cuaderno', 'libreta', 'carpeta', 'archivador', 'teclado', 'ratón de computadora', 'pantalla', 'impresora',
  'altavoz', 'auriculares', 'micrófono', 'cámara de fotos', 'trípode', 'flash', 'película', 'álbum',
  'guitarra eléctrica', 'bajo', 'batería', 'tambor', 'pandereta', 'flauta', 'trompeta', 'saxofón',
  'violín', 'arpa', 'piano', 'teclas', 'micrófono de pie', 'nota musical', 'disco', 'tocadiscos',
  'radio', 'cassette', 'bocina', 'campana de iglesia', 'campanario', 'iglesia', 'mezquita', 'templo',
  'pagoda', 'pirámide', 'esfinge', 'coliseo', 'casa de campo', 'cabaña', 'iglú', 'tienda de campaña',
  'fogata', 'leños', 'hoguera', 'malvavisco', 'cantimplora', 'brújula de mano', 'mochila de camping', 'saco de dormir',
  'linterna de mano', 'navaja suiza', 'cuerda', 'nudo', 'ancla de barco', 'boya naranja', 'barco de vela', 'velero',
  'yate', 'kayak', 'canoa', 'remo', 'bote', 'lancha', 'jet ski', 'ancla pequeña',
  'pingüino de juguete', 'oso de peluche', 'muñeca', 'tren de juguete', 'coche de juguete', 'cometa de papel', 'yoyo', 'peonza',
  'canica', 'dado', 'dominó', 'ajedrez', 'torre de ajedrez', 'caballo de ajedrez', 'alfil', 'peón',
  'barco de papel', 'avión de papel', 'cometa triangular', 'molinete', 'burbuja', 'varita de burbujas', 'pompas', 'globo terráqueo',
  'mapa mundial', 'bandera pirata', 'bandera de cuadros', 'porra', 'bomba de feria', 'algodón de azúcar', 'paleta', 'helado de cono',
  'nieve raspada', 'waffle de helado', 'banana split', 'manzana caramelizada', 'palomita', 'galleta de jengibre', 'hombre de jengibre', 'casa de jengibre',
  'campana navideña', 'bota navideña', 'árbol de navidad', 'regalo navideño', 'reno', 'trineo de santa', 'estrella fugaz', 'cometa de nieve',
];
